---

- name: Check if k3s zone already exists
  shell: firewall-cmd --permanent --zone=k3s  --list-sources
  register: fw_check
  failed_when: false
  changed_when: false


- name: Add k3s zone to firewalld and set rules
  shell: "firewall-cmd --permanent {{ item }}"
  with_items:
    - --new-zone=k3s
    - --zone=k3s --set-target=ACCEPT
    - --zone=k3s --add-source=10.42.0.0/16
    - --zone=k3s --add-interface=cni0
  when:
    - fw_check is not skipped
    - fw_check.rc != 0

- name: Reload firewalld to apply zone rules
  service:
    name: firewalld
    state: reloaded
